### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security følger policyen for fast livs syklus.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: nb-NO
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908840"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security følger policyen for [fast](/lifecycle/policies/fixed) livs syklus.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Koblinger \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security er utgått. Kunde støtte avslutter Juli 14th 2015. Antimalware og definisjons oppdateringer for antispionvare vil ikke lenger være tilgjengelig etter slutten av støtten for produkt versjonen. Evaluer ende punkt beskyttelse for System Center som erstatning."
