### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6 følger den faste livssykluspolicyen.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Windows Desktops,Sequencer
  ms.openlocfilehash: fb533aa91b47539b019872143dbfa2fcdd3d5cb0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: nb-NO
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4127700"
name: Microsoft Application Virtualization 4.6
summary: >+
  Microsoft Application Virtualization 4.6 følger den [faste](/lifecycle/policies/fixed) livssykluspolicyen.


  Dette gjelder for følgende versjoner: for Remote Desktop Services, for Windows Desktops, Sequencer

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Koblinger \n* [Produkt- og overføringsinformasjon](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Veiledning for overføring](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Policy for oppdateringspakke](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Siden App-V 4.6-klienten bruker App-V 4.5-serveren, vil App-V 4.5-serveren fortsatt støttes i henhold til livssyklusdatoene for App-V 4.6 når den er i bruk med den støttede App-V 4.6-klienten.\n\n## <a name=\"editions\"></a>Utgaver \n* for Remote Desktop Services\n* for Windows Desktops\n* Sequencer"
