### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 følger policyen for fast livssyklus.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 følger policyen for [fast](/lifecycle/policies/fixed) livssyklus.


  > [!IMPORTANT]
  > Støtte for dette produktet er avsluttet Se overføringsveiledning nedenfor.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Koblinger 
  * [Veiledning for overføring](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Ytterligere overføringsveiledning](/mem/configmgr/core/migration/planning-for-migration)