### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security følger policyen for fast livssyklus.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security følger policyen for [fast](/lifecycle/policies/fixed) livssyklus.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Koblinger 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security er avviklet fra og med 14. juli 2015. Definisjonsoppdateringer for beskyttelse mot skadelig programvare og antispionvare vil ikke lenger være tilgjengelige etter at støtten for produktversjonen er avsluttet. Vurder System Center Endpoint Protection som en erstatning.