### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security følger policyen for fast livssyklus.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: HT
  ms.contentlocale: nb-NO
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924265"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security følger policyen for [fast](/lifecycle/policies/fixed) livssyklus.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Koblinger \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security er avviklet fra og med 14. juli 2015. Definisjonsoppdateringer for beskyttelse mot skadelig programvare og antispionvare vil ikke lenger være tilgjengelige etter at støtten for produktversjonen er avsluttet. Vurder System Center Endpoint Protection som en erstatning."
