### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 for Windows-skrivebord
  description: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops følger den faste livssykluspolicyen.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: nb-NO
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "859600"
name: Microsoft Application Virtualization Hosting 5.1 for Windows-skrivebord
summary: >+
  Microsoft Application Virtualization Hosting 5.1 for Windows Desktops følger den [faste](/lifecycle/policies/fixed) livssykluspolicyen.


  Dette gjelder følgende utgaver: for Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Koblinger \n* [Produktinformasjon](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Utgaver \n* for Windows Desktops"
