### YamlMime:Lifecycle
metadata:
  title: SoftGrid-programvirtualisering
  description: SoftGrid Application Virtualization følger policyen for fast livssyklus.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: nb-NO
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "830302"
name: SoftGrid-programvirtualisering
summary: >
  SoftGrid Application Virtualization følger policyen [for fast](/lifecycle/policies/fixed) livssyklus.


  Dette gjelder følgende utgaver: 4.1 for stasjonære PC-er, 4.2 for stasjonære pc-er, for Terminal Services 4.1


  > [!IMPORTANT]

  > Støtten er avsluttet. Se overføringsveiledning nedenfor.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Koblinger \n* [Overføringsveiledning](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Utgaver \n* 4.1 for stasjonære PC-er\n* 4.2 for stasjonære PC-er\n* for Terminal Services 4.1"
