### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization følger den faste livssykluspolicyen.
  ms.date: 09/10/2020
  keywords: 4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1
  ms.openlocfilehash: 5009a44f0d0ab2b180f62474de8f4d4bb01e3e62
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: nb-NO
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1001029"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization følger den [faste](/lifecycle/policies/fixed) livssykluspolicyen.


  Dette gjelder for følgende versjoner: 4.1 for stasjonære PC-er, 4.2 for stasjonære PC-er, for Terminal Services 4.1


  > [!IMPORTANT]

  > Støtten er avsluttet. Se overføringsveiledning nedenfor.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Koblinger \n* [Veiledning for overføring](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Utgaver \n* 4.1 for stasjonære PC-er\n* 4.2 for stasjonære PC-er\n* for Terminal Services 4.1"
